### ISSUE TITLE
The NuGet v.1.0.1 contains an additional module

### ISSUE THREAD

**Issue by petgus** [davidknipe/VisualCompare#1]
A module named VisualGroupUsage is included in the content folder for VisualCompareMode 1.0.1
That module belongs in another NuGet doesn't it?
![screenshot_050818_121226_pm](https://user-images.githubusercontent.com/10164193/39751646-13c228fc-52b9-11e8-8512-bdae71ce2766.jpg)

**Comment by davidknipe** [comment]
Ah well spotted! Thanks for reporting. This has been sorted and v1.0.2 is now available on the Episerver Nuget feed.
