### ISSUE TITLE
Corrupt web.config.transform?

### ISSUE THREAD

**Issue by petgus** [davidknipe/VisualCompare#2]
Upgraded from v.1.0.2 > v.1.0.3

Got this error message when starting the site.
"Required attribute 'rootPath' not found"

Fixed it by re-inserting the rootPath attribute for episerver protectedModules.
` <episerver.shell>
        <publicModules rootPath="~/modules/" autoDiscovery="Modules" />
        <protectedModules rootPath="~/EPiServer/">
          ...
    </episerver.shell>`

Guessing it's caused by your web.config.transform file?
https://github.com/davidknipe/VisualCompare/blob/master/VisualCompareMode/web.config.transform

**Comment by davidknipe** [comment]
Thanks for raising the issue, as far as I am aware .transforms should merge config so should not have removed the rootPath attribute as you described. Can you re-create the issue on a standard Alloy site or was it specific to your build?

**Comment by davidknipe** [comment]
Could not recreate this issue so closing
