### ISSUE TITLE
Add-on not working on DXP 

### ISSUE THREAD

**Issue by tanujatbrightfind** [davidknipe/VisualCompare#6]
When trying to load Visual Compare add-on on DXP environment. It throws a "403" error in console.  and screen keeps spinning.

![image](https://user-images.githubusercontent.com/59699643/103019521-f8288680-4514-11eb-9d97-10e71e71a3d2.png)

![image](https://user-images.githubusercontent.com/59699643/103019563-0aa2c000-4515-11eb-9e5a-674e82192234.png)

Attn: @davidknipe

**Comment by tanujatbrightfind** [comment]
Version 1.0.3

**Comment by davidknipe** [comment]
Can you check the console for errors? The content security policy may be blocking something as 403's can be created when the csp blocks the request that generates the diff.

**Comment by tanujatbrightfind** [comment]
![image](https://user-images.githubusercontent.com/59699643/103030848-9ffc7f00-452a-11eb-9d58-df678fad2493.png)

Thanks for your response David. Please see attached screenshot. I can add content security policy to web.config,  Can you help me with right sources needed for the addon to work in DXP? 

Current value:

` <add name="Content-Security-Policy" value="default-src 'self' ws: wss: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://dc.services.visualstudio.com https://az416426.vo.msecnd.net https://code.jquery.com https://maxcdn.bootstrapcdn.com https://www.facebook.com *.episerver.net *.bing.com *.virtualearth.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com *.episerver.net *.bing.com https://maxcdn.bootstrapcdn.com; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com data:; connect-src 'self' https://dc.services.visualstudio.com ws: wss: *.bing.com *.virtualearth.net; img-src 'self' data: http: https:; child-src 'self' http://player.vimeo.com https://www.youtube.com" />`

Attn @davidknipe

**Comment by tanujatbrightfind** [comment]
Firewall error detail from cloudflare resulting in 403:

{
      "key": "group",
      "value": "cloudflare_specials"
    },
    {
      "key": "rule_message",
      "value": "XSS, HTML Injection - Script Tag"
    }
Attn @davidknipe

**Comment by davidknipe** [comment]
Thanks for the info, I will look into it. From memory it posts the html of each version to get the red/green comparison back. Sounds like Cloudflare inspects the request and sees it as potential script injection. Will try to recreate and see if there is a work around.

**Comment by davidknipe** [comment]
Pretty sure it's been blocked because of this line:

https://github.com/davidknipe/VisualCompare/blob/master/VisualCompareMode/modules/_protected/VisualCompareMode/Views/GetDiffBootstrapper.cshtml#L186 

It posts two sets of HTML to a server side controller method for the comparison version to be generated. So can you try replacing <project root>/modules/_protected/VisualCompareMode/Views/GetDiffBootstrapper.cshtml with this gist:

https://gist.github.com/davidknipe/bb9467a9bf51d6db785ec2699948c6c1

If it works then I will get update and push a new version out.

**Comment by davidknipe** [comment]
Hey @tanujatbrightfind did you manage to try the fix above?

**Comment by tanujatbrightfind** [comment]
Hi @davidknipe I tried testing using updated gist on DXP. I am seeing still seeing the same 403 output. 

![image](https://user-images.githubusercontent.com/59699643/103816570-2d63c700-5033-11eb-84c6-117a3b697065.png)

**Comment by davidknipe** [comment]
Hey @tanujatbrightfind can you try again (have updated the gist). I am guessing that perhaps your source code had <script> tags with an async or defer attribute or something that wasn't matched in the original gist.

**Comment by tanujatbrightfind** [comment]
hey @davidknipe 
I had to make a few changes to your gist. line 164,184 and 203. doing this replaced all script tags before doing POST.
I am still getting cloudflare error, a different one this time. attached is screenshot from console.

updated gist: https://gist.github.com/tanujatbrightfind/018e80153deb60da8b798131eb2c2316#file-getdiffbootstrapper-cshtml-L165


I will be reaching out to DXP support to find out more details about this cloudflare error. 
<img width="790" alt="Screen Shot 2021-01-11 at 10 04 45 AM" src="https://user-images.githubusercontent.com/59699643/104199480-7fbb3400-53f5-11eb-85ea-78f7419a2292.png">

**Comment by tanujatbrightfind** [comment]
Cloudflare error details:

Rule ID
OWASP Block (981176)

Rule message
Inbound Anomaly Score Exceeded (Total Score: 207, SQLi=27, XSS=135)

Rule group
OWASP Inbound Blocking

Action taken
Challenge

attn @davidknipe

**Comment by tanujatbrightfind** [comment]
@davidknipe Circling back to see, if you have other/new  ideas I can try to resolve this issue. Thanks.

**Comment by wezz** [comment]
Hi! Just raising my hand to say that we're seeing the same issue in our platform. 
It'd be great to get the visual comparison to work in the DXP environments. 

I've also contacted support to see what they can do, I've asked them to whitelist the URL but I don't think they'll do that.

**Comment by davidknipe** [comment]
> Hi! Just raising my hand to say that we're seeing the same issue in our platform. 
> 
> It'd be great to get the visual comparison to work in the DXP environments. 
> 
> 
> 
> I've also contacted support to see what they can do, I've asked them to whitelist the URL but I don't think they'll do that.

Thanks for your interest! I am going to look into ways of refactoring the code so it doesn't trigger the WAF rule in Cloudflare. I will post an updated version of the package here to test if you can help me test it?

**Comment by davidknipe** [comment]
Hi both, I have created a new version of the package. You can see the code on [this branch](https://github.com/davidknipe/VisualCompare/tree/bug-not-working-on-DXP) if you want to inspect it and download the Nuget package here:

[https://github.com/davidknipe/VisualCompare/blob/bug-not-working-on-DXP/Nuget/VisualCompareMode.1.0.6.nupkg](https://github.com/davidknipe/VisualCompare/blob/bug-not-working-on-DXP/Nuget/VisualCompareMode.1.0.6.nupkg) 

I'd appreciate your support in testing this updated version to see if it solves your problem. If it does I can submit it as an update to the public package.

For info I now base64 encode the html sent in the request to not make it look suspicious, as this is what appears to be triggering the WAF rule

**Comment by davidknipe** [comment]
Have just tried this on a DXP environment and it's looking good, so look forward to your feedback :)

**Comment by davidknipe** [comment]
Hi both, just wanted to check in and see if you have had a chance to test this on your DXP instances? I am pretty happy so will push the new version of the package and close this issue unless I hear back :)

**Comment by davidknipe** [comment]
Fixed: https://github.com/davidknipe/VisualCompare/pull/8
