### ISSUE TITLE
Typo in the drop-down menu

### ISSUE THREAD

**Issue by qtxasjo** [davidknipe/VisualCompare#7]
Please fix the typo in the 'Select compare mode' drop-down - "visual comparision" should be "visual comparison".

(Thank you so much for this add-on, @davidknipe! It's my favourite on World and I'm trying to get them to implement it as a core feature.)
![image](https://user-images.githubusercontent.com/26276682/114671817-c8d89800-9d04-11eb-96d2-cb7ec6a44856.png)

**Comment by davidknipe** [comment]
Hey Åsa, glad you like using this add on and thanks for spotting the typo. This has been fixed and v1.0.4 is available on the Nuget feed:

[https://nuget.episerver.com/package/?id=VisualCompareMode](https://nuget.episerver.com/package/?id=VisualCompareMode)
