### ISSUE TITLE
Typo in GetDiffBootstrapper.cshtml

### ISSUE THREAD

**Issue by birgitzprinz** [davidknipe/VisualCompare#9]
There is a typo error at line 191 in GetDiffBootstrapper.cshtml file. This issue causes a JS error on browser with the message: Uncaught ReferenceError: q is not defined

![image](https://user-images.githubusercontent.com/1060979/127302380-c7755007-5abd-4b7b-b1b3-1339deb6d3bf.png)

**Comment by davidknipe** [comment]
Fixed and available on the Nuget feed: https://nuget.optimizely.com/package/?id=VisualCompareMode&v=1.0.7
